source "https://rubygems.org"

ruby "3.2.3"

gem "rails", "~> 7.1.3", ">= 7.1.3.4"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "rack-cors"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
end

group :development do
  gem 'rubocop', require: false
end

gem 'dotenv-rails'
gem 'rails_same_site_cookie'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem "omniauth-rails_csrf_protection"
gem 'jwt'
gem 'pagy', '~> 9.0'
gem 'active_model_serializers'
